export const ansibleStack = [
'automation:',
'  tool: Ansible',
'  playbooks:',
'    - pull-and-run-image.yml',
'    - setup-directories.yml',
'',
'containerization:',
'  runtime: Docker',
'  orchestration: Docker Compose',
'  registry: GitHub Container Registry (GHCR)',
'',
'services:',
'  - Docker',
'  - Ansible',
'  - Git',
'',
'version_control:',
'  tool: Git',
'  flow: staging and prod branches',
'  env_files: shared manually (outside image)',
];