// File: components/fileData/aboutMeContent.ts
export const aboutMeContent: string[] = [
  "Hey, I'm Maad 👋",
  "",
  "I’m a DevOps engineer from Colombo, Sri Lanka, and my journey into tech didn’t start in a server room — ",
  "it started with curiosity. First came the love for tech, then the thrill of programming — writing lines of code ",
  "that actually did things. Useful things.",
  "",
  "During my internship, I stumbled into the world of DevOps, quite literally. One day I was just maintaining ",
  "WordPress pages, and the next I was configuring live Linux servers, writing deployment scripts, and learning ",
  "the hard way why mail servers hate static IPs (yes, I got blacklisted on every spam list in the galaxy 🌌).",
  "",
  "That moment — setting up my first real server, alone, from scratch — was when it clicked: this is what ",
  "I want to do. Automating boring stuff. Building systems that just *work*. Because honestly? Repeating ",
  "the same thing twice makes me want to bash my head against a Bash script.",
  "",
  "Since then, I’ve been the one-man tech army at a B2B firm trying to turn into a tech company. I wear ",
  "many hats (most of them DevOps-flavored) — from Docker wizardry to CI/CD pipelines, from email ",
  "verifiers to EDM tools. I built https://thevalid8.com solo, learned Redis, Celery, Postfix, and got humbled by ",
  "DNS configs I thought I understood.",
  "",
  "Outside work, I'm a scuba diver 🐠. Not a weekend hobbyist — I’m PADI Advanced, and diving is ",
  "how I reset. It’s quiet, it’s weightless, it’s a different world where it’s just me and the ocean. ",
  "It’s also where I steal all my metaphors from:",
  "",
  '  "Life’s like scuba diving — sometimes you just gotta dive in head first, roll with the currents, and embrace the unknown."',
  "",
  "I also love gaming, watching esports, exploring networking gear, and building personal projects ",
  "like my current baby: a DIY NAS. I tend to fall head-first into new obsessions (read: side quests), ",
  "learn everything I can, then hop onto the next — call me a jack of all tech trades.",
  "",
  "Let’s connect if you're into servers, ocean stuff, esports tactics, or just wanna chat about ",
  "why mail servers are still stuck in 1999.",
  "",
  "Links:",
  "- GitHub: https://github.com/Nightwalker28",
  "- LinkedIn: https://www.linkedin.com/in/maad-mustafa/",
  "- Dev.to: https://dev.to/nightwalker28",
  "- Website: https://maad.dev",
  "- Insta (if you're curious): https://www.instagram.com/maad_4570/",
];