// File: components/fileData/resumeContent.ts
export const resumeContent: string[] = [
  "name: Maad Mustafa",
  "title: DevOps Engineer",
  "location: Colombo, Sri Lanka",
  "email: maadmustafa28@gmail.com",
  "links:",
  "  github: https://github.com/Nightwalker28",
  "  linkedin: https://linkedin.com/in/maad-mustafa",
  "  devto: https://dev.to/nightwalker28",
  "  website: https://maad.dev",
  "summary: >",
  "  Junior DevOps Engineer with a strong foundation in Computer Science",
  "  and experience in AWS, Docker, Kubernetes, and automation tools",
  "  like Jenkins and Terraform. Focused on building scalable",
  "  infrastructure and optimizing systems.",
  "experience:",
  "  - role: Junior DevOps Engineer",
  "    company: Acumen Intelligence",
  "    duration: Jan 2024 – Present",
  "    highlights:",
  "      - Built and launched thevalid8.com, an email verification platform.",
  "      - Managed server configurations and network optimization.",
  "      - Developed an EDM tool to streamline marketing.",
  "      - Set up automated deployments using Docker and GitHub Actions.",
  "",
  "  - role: Campaign Executive",
  "    company: Acumen Intelligence",
  "    duration: Feb 2023 – Jan 2024",
  "    highlights:",
  "      - Executed and optimized email marketing campaigns.",
  "      - Contributed to overall marketing strategy and growth.",
  "",
  "skills:",
  "  cloud_devops: [AWS, Docker, Kubernetes, Terraform, Ansible, Jenkins, GitHub Actions]",
  "  languages: [Python, JavaScript, Java, SQL, Bash]",
  "  frameworks: [Flask, Node.js, React]",
  "  databases: [MySQL, PostgreSQL, Redis, Celery]",
  "  systems: [Linux Server Administration, NGINX, SSL]",
  "",
  "education:",
  "  degree: BEng in Computer Science",
  "  institution: University of Westminster",
  "  duration: Sept 2021 – Jun 2026",
];